#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# uploads specified files to the repo
#

REPOHOST="pkgs.tribblix.org"
REPODIR="/var/repo"
REPOVER="m30"
REPOTYPE=".sparc"

case $1 in
    -r)
	REPOVER="$2"
	shift
	shift
	;;
esac

REPO="overlays-${REPOVER}${REPOTYPE}"

#
# sanity check
#
if [ ! -d "$THOME" ]; then
    echo "Cannot find my home"
    exit 1
fi

case $# in
    0)
	echo "Usage: $0 file [...]"
	exit 1
	;;
esac

for file in $*
do
    if [ ! -f $file ]; then
	echo "ERROR: Missing file $file"
	exit 1
    fi
done

#
scp $* ${REPOHOST}:${REPODIR}/${REPO}
